"""
Central configuration for the Phase 1 core pipeline (chunk -> embed -> index
-> retrieve -> prompt -> generate).

Single source of truth for every RAG-pipeline constant, mirroring the
corpus-preparation config (hypeonoath/ingestion/config.py). Folder paths come
from hypeonoath.core.paths, shared with ingestion, so the two can never
disagree about where files live.
Values marked "tune" are starting points from
plans/phase1-core-pipeline-code-implementation-guideline-v4.md, to be tuned
against the eval set / real corpus -- not fixed specs.
"""
from __future__ import annotations

from hypeonoath.core import paths

# --- Paths (shared with corpus preparation, via core.paths) -----------------
PROJECT_ROOT = paths.PROJECT_ROOT
CORPUS_DIR = paths.CORPUS_DIR
CODE_DIR = paths.CODE_DIR
DOCUMENTS_DIR = paths.DOCUMENTS_DIR
CONVERTED_DIR = paths.CONVERTED_DIR
CODE_METADATA_PATH = paths.CODE_METADATA_PATH
DOCLING_JSON_SUFFIX = paths.DOCLING_JSON_SUFFIX
LOGS_DIR = paths.LOGS_DIR

# Phase 1 logs follow Phase 0's corpus/.logs/*.jsonl convention.
CODE_CHUNKING_LOG_PATH = LOGS_DIR / "code_chunking.jsonl"
DOCUMENT_LOADING_LOG_PATH = LOGS_DIR / "document_loading.jsonl"
INDEXING_LOG_PATH = LOGS_DIR / "indexing.jsonl"
SCAN_WARNINGS_PATH = LOGS_DIR / "scan_warnings.jsonl"   # guideline 3A.13
SCAN_ALLOWLIST_PATH = CORPUS_DIR / ".scan_allowlist.yaml"

# Virtual source path for project-summary chunks (guideline 3A.12).
PROJECT_SUMMARY_SOURCE_PREFIX = "corpus/code/_projects/"

# --- Chroma (ADR-5, Section 5) ----------------------------------------------
# A plain on-disk directory, committed with the code (design doc 9.1,
# Option A).
CHROMA_DIR = paths.INDEX_DIR / "chroma"
COLLECTION_NAME = "corpus"

# --- Embedding model (Section 4; user decision 2026-09-30) ------------------
EMBED_MODEL_NAME = "nomic-ai/nomic-embed-text-v1.5"
# Pinned Hugging Face commit, so remote code + weights can't change under us
# (Section 2.2 invariant). Resolved from the Hub on 2026-10-01.
EMBED_MODEL_REVISION = "e9b6763023c676ca8431644204f50c2b100d9aab"
# Model card: trust_remote_code is no longer needed from transformers v5.5.0 /
# sentence-transformers v5.3.0. Verified 2026-10-01: loads natively with the
# pinned transformers 5.18.0 / sentence-transformers 6.1.0 (no remote code).
EMBED_TRUST_REMOTE_CODE = False
EMBED_MAX_TOKENS = 8192          # model's hard input limit (safety cap only)
EMBED_DIM = 768
EMBED_BATCH_SIZE = 16
DOC_PREFIX = "search_document: "  # nomic task prefixes -- compulsory
QUERY_PREFIX = "search_query: "

# --- Prose / table chunking (Section 3) -------------------------------------
PROSE_MIN_TOKENS = 300           # tune -- soft target
PROSE_MAX_TOKENS = 500           # tune -- includes heading line + DOC_PREFIX
PROSE_OVERLAP_RATIO = 0.12       # ~10-15% between consecutive chunks of one group

# --- Code chunking (Section 3A) ---------------------------------------------
CODE_TARGET_TOKENS = 512         # tune -- precision budget, whole chunk text
HEADER_TOKEN_RESERVE = 48        # tune -- raise (not shorten names) if exceeded
FALLBACK_OVERLAP_RATIO = 0.10    # line-window fallback overlap
ERROR_NODE_FALLBACK_RATIO = 0.20  # tune -- share of ERROR bytes forcing fallback

MAX_CODE_FILE_BYTES = 200_000    # tune
MAX_LINE_CHARS = 1000            # tune -- catches minified code
GENERATED_MARKER_LINES = 5

EXCLUDED_DIR_PARTS: frozenset[str] = frozenset(
    {"node_modules", "vendor", "dist", "build", ".venv", "__pycache__", ".git"}
)
EXCLUDED_NAME_SUFFIXES: tuple[str, ...] = (".min.js", ".min.css", ".bundle.js", ".map")
GENERATED_MARKERS: tuple[str, ...] = (
    "code generated",          # Go: "// Code generated ... DO NOT EDIT."
    "do not edit",
    "@generated",
    "autogenerated",
    "auto-generated",
)

# Extension -> tree-sitter-language-pack grammar name (3A.4 Step 5). Every
# name is verified with get_language() by code_chunker.self_check().
EXT_TO_LANGUAGE: dict[str, str] = {
    ".py": "python",
    ".js": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "tsx",
    ".java": "java",
    ".c": "c", ".h": "c",          # .h retried as cpp on a bad c parse
    ".cpp": "cpp", ".hpp": "cpp", ".cc": "cpp",
    ".cs": "csharp",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".swift": "swift",
    ".kt": "kotlin", ".kts": "kotlin",
    ".scala": "scala",
    ".sh": "bash", ".bash": "bash",
    ".sql": "sql",
    ".html": "html",
    ".css": "css", ".scss": "scss",
    ".r": "r",
    ".pl": "perl",
    ".lua": "lua",
    ".dart": "dart",
}
NOTEBOOK_EXTENSION = ".ipynb"
NOTEBOOK_DEFAULT_LANGUAGE = "python"

# --- Retrieval / prompting (Sections 6, 7) ----------------------------------
DEFAULT_TOP_K = 8                # tune against the eval set
MAX_CONTEXT_TOKENS = 6000        # tune -- chunk context budget in the prompt
REFUSAL_PHRASE = "I don't have information about that in my documents"

# --- Generation: local Ollama, Phase 1 only (ADR-4) -------------------------
OLLAMA_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama3.1:8b"
OLLAMA_NUM_CTX = 8192            # Ollama's default context is too small for k=8
OLLAMA_TIMEOUT_SECONDS = 300

# --- Pinned library versions (3A.4 Step 0) -----------------------------------
# Recorded here next to the model name so a version change is a deliberate,
# reviewed re-index (chunk boundaries -> chunk_ids -> the committed index).
# Must match the exact pins in pyproject.toml.
PINNED_VERSIONS: dict[str, str] = {
    "chonkie": "1.7.0",
    "chonkie-core": "0.10.2",
    "tree-sitter-language-pack": "1.20.0",
    "tree-sitter": "0.26.0",
    "sentence-transformers": "6.1.0",
    "transformers": "5.18.0",
    "torch": "2.14.1",
    "chromadb": "1.5.9",
    "detect-secrets": "1.5.0",
    "nbformat": "5.11.1",
    "markdown-it-py": "4.2.0",
    "docling-core": "2.99.0",
}
